---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/smi-controller-webhook-certificate"
  name: blah
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ include "smi-controller.fullname" . }}'