---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smi-manager-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups: ["access.smi-spec.io", "split.smi-spec.io"]
  resources:
  - traffictargets
  - trafficsplits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
# permissions for end users to edit traffictargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smi-editor-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups: ["access.smi-spec.io", "split.smi-spec.io"]
  resources:
  - traffictargets
  - trafficsplits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
# permissions for end users to view traffictargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smi-viewer-role
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true" 
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true" 
rules:
- apiGroups: ["access.smi-spec.io", "split.smi-spec.io"]
  resources:
  - traffictargets
  - trafficsplits
  verbs:
  - get
  - list
  - watch
