kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "smi-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: smi-manager-role
  apiGroup: rbac.authorization.k8s.io

