apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smi-controller-leader-election-rolebinding
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smi-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: smi-controller-controller-manager
  namespace: '{{ .Release.Namespace }}'
