name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Unit Test
      run: go test -v ./...

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash
        shipyard run ./shipyard

    - name: Setup Kubebuilder
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)

        # download kubebuilder and extract it to tmp
        curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

        # move to a long-term location and put it on your path
        # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
        mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
    
    - name: Run Functional Tests
      run: |
        eval $(shipyard env)
        make functional_test