name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Unit Test
      run: go test -v ./...

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash
        shipyard run ./shipyard
        KUBECONFIG=$(shipyard output KUBECONFIG) make test_functional

    - name: Execute Functional Tests
      run: |
        cd test && go run .
